-- MySQL Script generated by MySQL Workbench
-- Mon Aug  1 10:39:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `test_db` ;

-- -----------------------------------------------------
-- Schema test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `test_db` ;

-- -----------------------------------------------------
-- Table `test_db`.`backup_employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`backup_employee` ;

CREATE TABLE IF NOT EXISTS `test_db`.`backup_employee` (
  `b_id` INT NOT NULL,
  `b_last_name` VARCHAR(255) NULL DEFAULT NULL,
  `b_first_name` VARCHAR(255) NULL DEFAULT NULL,
  `b_gender` VARCHAR(10) NULL DEFAULT NULL,
  `b_dept` VARCHAR(10) NULL DEFAULT NULL,
  `b_birth` DATE NULL DEFAULT NULL,
  `b_email` VARCHAR(255) NULL DEFAULT NULL,
  `b_tel_no` VARCHAR(255) NULL DEFAULT NULL,
  `b_zip` VARCHAR(255) NULL DEFAULT NULL,
  `b_address1` VARCHAR(255) NULL DEFAULT NULL,
  `b_address2` VARCHAR(255) NULL DEFAULT NULL,
  `b_address3` VARCHAR(255) NULL DEFAULT NULL,
  `b_school1` VARCHAR(255) NULL DEFAULT NULL,
  `b_school2` VARCHAR(255) NULL DEFAULT NULL,
  `b_skill` VARCHAR(255) NULL DEFAULT NULL,
  `b_image` VARCHAR(255) NULL DEFAULT NULL,
  `dt` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`b_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_db`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`employee` ;

CREATE TABLE IF NOT EXISTS `test_db`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `dept` VARCHAR(10) NULL DEFAULT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `tel_no` VARCHAR(255) NULL DEFAULT NULL,
  `zip` VARCHAR(255) NULL DEFAULT NULL,
  `address1` VARCHAR(255) NULL DEFAULT NULL,
  `address2` VARCHAR(255) NULL DEFAULT NULL,
  `address3` VARCHAR(255) NULL DEFAULT NULL,
  `school1` VARCHAR(255) NULL DEFAULT NULL,
  `school2` VARCHAR(255) NULL DEFAULT NULL,
  `skill` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 494
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_db`.`operationlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`operationlog` ;

CREATE TABLE IF NOT EXISTS `test_db`.`operationlog` (
  `log_no` INT NOT NULL AUTO_INCREMENT,
  `ope_name` VARCHAR(255) NULL DEFAULT NULL,
  `ope` VARCHAR(255) NULL DEFAULT NULL,
  `target` VARCHAR(255) NULL DEFAULT NULL,
  `result` VARCHAR(255) NULL DEFAULT NULL,
  `log_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`log_no`))
ENGINE = InnoDB
AUTO_INCREMENT = 1028
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `test_db`.`usr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test_db`.`usr` ;

CREATE TABLE IF NOT EXISTS `test_db`.`usr` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `roles` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;

INSERT INTO `usr` (`user_id`, `email`, `password`, `roles`) VALUES 
(4, 'admin@co.jp', '$2a$10$BeZ9SPkbMmYi3HZ2TMwLMuJ.NfxJOCQg43.D1em37GMiw52wdSQXW' ,'ADMIN');

INSERT INTO `usr` (`user_id`, `email`, `password`, `roles`) VALUES 
(5, 'user@co.jp', '$2a$10$BeZ9SPkbMmYi3HZ2TMwLMuJ.NfxJOCQg43.D1em37GMiw52wdSQXW' ,'USER');



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `test_db`;

DELIMITER $$

USE `test_db`$$
DROP TRIGGER IF EXISTS `test_db`.`trigger_e_backup` $$
USE `test_db`$$
CREATE
DEFINER=`test`@`localhost`
TRIGGER `test_db`.`trigger_e_backup`
AFTER DELETE ON `test_db`.`employee`
FOR EACH ROW
begin 
   insert into `backup_employee`
   set
    `b_id` = old.`id`,
    `b_last_name` = old.`last_name`,
    `b_first_name` = old.`first_name`,
    `b_gender` = old.`gender`,
    `b_dept` = old.`dept`,
    `b_birth` = old.`birth`,
    `b_email` = old.`email`,
    `b_tel_no` = old.`tel_no`,
    `b_zip` = old.`zip`,
    `b_address1` = old.`address1`,
    `b_address2` = old.`address2`,
    `b_address3` = old.`address3`,
    `b_school1` = old.`school1`,
    `b_school2` = old.`school2`,
    `b_skill` = old.`skill`,
    `b_image` = old.`image`,
    `dt` = now();
    end$$


DELIMITER ;
